### ISSUE TITLE
Issue when only a single user has passkeys/fido

### ISSUE THREAD

**Issue by SeSeKenny** [f-bader/EntraIDPasskeyHelper#1]
In the function Get-PasskeyDeviceBoundAAGUID there is an issue when $ReturnValue only contains 1 entry, basically $PassKeyDeviceBoundUsers is not seen as an array for the range operator building up $Requests.

Changing line from,
$Requests = $PassKeyDeviceBoundUsers[$i..($LastItem)] | ForEach-Object {
to
$Requests = (,$PassKeyDeviceBoundUsers)[$i..($LastItem)] | ForEach-Object {

resolves this as it forces array interpretation. Could be done in other ways, just wanted something quick :)

Error is 
{"error":{"code":"BadRequest","message":"Invalid batch payload format."
which is traced to
PS /home/user> $requestParams.Body
{
  "requests": []
}

**Comment by brianreidc7** [comment]
Can confirm this is an issue. Found it in a number of tenants. Another quick and dirty fix for anyone with this issue is to

Changing line above to (i.e. remove the array handling),
$Requests = $PassKeyDeviceBoundUsers | ForEach-Object {

**Comment by f-bader** [comment]
Just commit a fix for this issue. Will be in the gallery soon

**Comment by f-bader** [comment]
Release is published
https://www.powershellgallery.com/packages/EntraIDPasskeyHelper/1.0.2
